#!/bin/sh
set -e

if [ "$1" = "configure" ]
then
  groupadd -r futurehome || true
  groupadd -r ecollector || true

  useradd -r -N -M -d / -s /bin/false -g ecollector ecollector || true

  chown -R ecollector:futurehome /var/log/futurehome/ecollector/ || true
  chown -R ecollector:ecollector /var/lib/futurehome/ecollector/ || true
fi

deb-systemd-helper unmask ecollector.service >/dev/null || true

if deb-systemd-helper --quiet was-enabled ecollector.service; then
  systemctl enable ecollector.service || true
else
  deb-systemd-helper update-state ecollector.service >/dev/null || true
fi

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true

  if [ -n "$2" ]; then
    deb-systemd-invoke try-restart ecollector.service >/dev/null || true
  else
    deb-systemd-invoke start ecollector.service >/dev/null || true
  fi
fi